version: "3.7"

services:
    app:
        build:
            args:
                - user:root
                - uid:1
            context: ./
            dockerfile: Dockerfile
        image: smith
        container_name: smith-app
        restart: unless-stopped # always restart if not stopped
        working_dir: /var/www
#        expose:
#            -   9000
        volumes: # sync local data and container
            -  ./:/var/www
#            - ./.docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        networks:
            - smith
    db:
        image: mysql:5.7
        container_name: smith-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - "33307:3306"
#        volumes:
#            - ./.docker/mysql:/docker-entrypoint-initdb.d
        networks:
            - smith
    nginx:
        image: nginx:1.23.0
        container_name: smith-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            -   ./:/var/www
            -   .docker/nginx:/etc/nginx/conf.d
        networks:
            - smith
networks:
    smith:
        driver: bridge
